"""Deterministic calculation for product sales velocity."""


def calculate_sales_velocity(total_units_sold: int, observation_period_days: int) -> float:
    """
    Calculate product sales velocity (average units sold per calendar day).

    Formula:
        velocity = total_units_sold / observation_period_days

    Assumptions & Guarantees:
        - observation_period_days must be >= 1. If <= 0, defaults to 1 day.
        - total_units_sold must be >= 0.
        - Returns float rounded to 4 decimal places.

    Example:
        120 units sold over 30 days = 4.0 units/day
    """
    days = max(1, observation_period_days)
    units = max(0, total_units_sold)
    return round(units / days, 4)


def calculate_average_daily_revenue(total_revenue: float, observation_period_days: int) -> float:
    """
    Calculate average daily revenue generated by a product or business.

    Formula:
        daily_revenue = total_revenue / observation_period_days
    """
    days = max(1, observation_period_days)
    rev = max(0.0, total_revenue)
    return round(rev / days, 2)
