"""
Mock LLM Provider — deterministic development/test provider.

Behavior:
  - Returns a valid InvestigationResponse-shaped JSON string.
  - Parses key facts from the user_prompt text to produce context-aware output.
  - Requires zero external API calls.
  - Clearly marked as MOCK mode throughout.

Usage:
  LLM_PROVIDER=mock  (default; no API key required)
"""
import json
import re


class MockLLMProvider:
    """
    Deterministic mock provider for development, testing, and CI.

    Does NOT call any external service.
    Does NOT pretend to be real AI reasoning.
    Does NOT fabricate business numbers.
    """

    async def generate(self, system_prompt: str, user_prompt: str) -> str:
        """Return a deterministic, context-aware mock investigation response."""
        revenue_match = re.search(r"Total Revenue:\s*\$([\d,\.]+)", user_prompt)
        transactions_match = re.search(r"Total Completed Transactions:\s*(\d+)", user_prompt)
        low_stock_match = re.search(r"Low Stock Alerts:\s*(\d+)", user_prompt)
        oos_match = re.search(r"Out of Stock SKUs:\s*(\d+)", user_prompt)

        revenue_str = f"${revenue_match.group(1)}" if revenue_match else "unavailable"
        tx_str = transactions_match.group(1) if transactions_match else "unavailable"
        low_stock_str = low_stock_match.group(1) if low_stock_match else "0"
        oos_str = oos_match.group(1) if oos_match else "0"

        has_kpis = "VERIFIED EXECUTIVE KPIS" in user_prompt and "No KPI data" not in user_prompt
        confidence = "MEDIUM" if has_kpis else "LOW"

        question_match = re.search(
            r"--- USER INVESTIGATION QUESTION ---\n(.+?)(?:\n\nAnalyze|$)",
            user_prompt, re.DOTALL
        )
        question = question_match.group(1).strip() if question_match else "Business investigation"

        limitations = ["This response was generated by the NEXUS mock provider (LLM_PROVIDER=mock)."]
        if not has_kpis:
            limitations.append("No business KPI data was available in the analytics context.")

        response = {
            "question": question,
            "answer": (
                f"[MOCK MODE] Based on the verified NEXUS business context, the observation window shows "
                f"revenue of {revenue_str} across {tx_str} transactions. "
                f"There are {low_stock_str} low-stock alerts and {oos_str} out-of-stock SKUs. "
                "Review the inventory risk matrix and deterministic advisories above for specific actions. "
                "Switch LLM_PROVIDER to 'gemini' (with a valid API key) for AI-powered analysis."
            ),
            "key_findings": [
                f"Revenue for the observation period: {revenue_str}",
                f"Completed transactions: {tx_str}",
                f"Low stock alerts: {low_stock_str} | Out of stock SKUs: {oos_str}",
            ],
            "recommendations": [
                "Review the deterministic recommendations from the NEXUS rule-based engine above.",
                "Configure a real LLM provider (LLM_PROVIDER=gemini) for AI-powered interpretation.",
            ],
            "supporting_facts": [
                f"Revenue (from database aggregation): {revenue_str}",
                f"Completed transactions (from database): {tx_str}",
                f"Low stock count (from deterministic risk engine): {low_stock_str}",
                f"Out of stock count (from deterministic risk engine): {oos_str}",
            ],
            "confidence": confidence,
            "limitations": limitations,
        }

        return json.dumps(response)
